### ISSUE TITLE
why is everything in /src/test

### ISSUE THREAD

**Issue by darthShana** [0x3333/dagger-aop-logger#1]
Hi 
Sorry im fairly new to dagger, so please forgive if this is noob question..
But why is everything in /src/test ?

Im trying to create a new aop injection project.. And im confused about  InterceptorModule.java
its generated in test-annotations
which excludes it from the created artifact. So im not able to use it in my porject

**Comment by 0x3333** [comment]
Hi, the src/test are the tests, the source code itself is on src/main.

To use the project, you need to package and install on your local maven repo.

```
git clone git@github.com:0x3333/dagger-aop-logger.git
cd dagger-aop-logger
mvn clean install
```

And import into your project:

```
  <dependency>
      <groupId>com.github.0x3333.dagger.aop</groupId>
      <artifactId>dagger-aop-logger</artifactId>
      <version>1.0-SNAPSHOT</version>
  </dependency>
```

Then you are ready to go.

**Comment by darthShana** [comment]
but what about this step
"Add to you Dagger Module the InterceptorModule and a @Provides for LogInterceptor."

**Comment by 0x3333** [comment]
To YOUR Dagger Module you add:

```
 @Provides
  static LogInterceptor providesLogInterceptor() {
    return new LogInterceptor();
  }
```

This will bind the LogInterceptor class in the dagger graph.

**Comment by darthShana** [comment]
hmm. ok but as per your documentation
`// Adding InterceptorModule
@Module(includes = { InterceptorModule.class })
public abstract class MyModule {

  @Binds
	MyService providesMyService(MyClass impl);
	
  @Provides
  static LogInterceptor providesLogInterceptor() {
    return new LogInterceptor();
  }

}`

So do i need ?
`@Binds
	MyService providesMyService(MyClass impl);`

**Comment by 0x3333** [comment]
It is exactly what it says. This is a "imaginary" module.  You have to add InterceptorModule and the provides in your module.

```
// Adding InterceptorModule
@module(includes = { InterceptorModule.class })
public abstract class MyModule {

@provides
static LogInterceptor providesLogInterceptor() {
return new LogInterceptor();
}

}
```

**Comment by darthShana** [comment]
Im so sorry if these are dumb questions but if 
public abstract class MyModule {
is the module in "my project"
it would be in
src/main/java/com.dathShana.sample.modules/MyModule.java
How can i add a dependancy on InterceptorModule.class which gets generated in
src/test/....

thank you for your responses

**Comment by 0x3333** [comment]
The src/test InterceptorModule is the module generated by the APT to the test package, APT should generate a InterceptorModule for you binds.

The InterceptorModule is a module that is generated with binds to all generated classes.

**Comment by 0x3333** [comment]
The minimal setup example is the test itself...
