### ISSUE TITLE
InterceptorModule

### ISSUE THREAD

**Issue by darthShana** [0x3333/dagger-aop-logger#2]
Im confused about this step
"Add to you Dagger Module the InterceptorModule and a @provides for LogInterceptor."

as the documentation suggests i did
`git clone git@github.com:0x3333/dagger-aop-logger.git
cd dagger-aop-logger
mvn clean install
`
and then included 
`<dependency>
      <groupId>com.github.0x3333.dagger.aop</groupId>
      <artifactId>dagger-aop-logger</artifactId>
      <version>1.0-SNAPSHOT</version>
  </dependency>`

in my new project "dagger-hello-world". 
but im guessing i will have to add InterceptorModule to my dagger-hello-world dagger module. But InterceptorModule is not included in the dagger-aop-logger artifact

**Comment by 0x3333** [comment]
The `InterceptorModule` module is generated by the annotation processor...
